name: ci

on: [push]

jobs:
  build_r:
    runs-on: ubuntu-16.04
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: https://demo.rstudiopm.com/all/__linux__/xenial/latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 3.6
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        # build client code
      - run: npm i -g yarn
      - run: yarn set version berry
      - run: yarn config set checksumBehavior ignore
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ./.yarn
          key: ${{ runner.os }}-yarn2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-
      - run: yarn install --immutable
        env:
          CI: true
      - run: yarn build
        env:
          CI: true

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-v2-${{ hashFiles('r_package/DESCRIPTION')}}
          restore-keys: ${{ runner.os }}-r-v2-

      # - name: Install system dependencies
      #   env:
      #     RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
      #   run: |
      #     Rscript -e "remotes::install_github('r-hub/sysreqs')"
      #     sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
      #     sudo -s eval "$sysreqs"

      - name: Install dependencies
        run: |
          install.packages('devtools')
          install.packages('pkgdown')
          install.packages('webshot')
          devtools::install_deps('r_package', dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: devtools::check('r_package', args = c("--no-manual", "--as-cran"), error_on = "error", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-results
          path: r_package/check

      - name: Build Package
        run: yarn build:r
      - name: Prepare Docs
        run: |
          mkdir -p public/integrations/r
          cp ./upsetjs.tar.gz public/integrations/r/
          cp README.md r_package/
      - name: Build Website
        run: yarn docs:r
      - name: Copy Docs
        run: |
          mv r_package/docs/* public/integrations/r/

      - name: Deploy Master
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: upsetjs/actions-gh-pages@sgratzl
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: upsetjs/upsetjs.github.io
          publish_branch: master
          publish_dir: ./public
          enable_jekyll: true
          remove_path_spec: 'integrations/r/'

      - if: github.ref == 'refs/heads/develop'
        # move to next directory
        run: |
          mv public public2
          mkdir -p public
          mv public2 public/next

      - name: Deploy Develop
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        uses: upsetjs/actions-gh-pages@sgratzl
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: upsetjs/upsetjs.github.io
          publish_branch: master
          publish_dir: ./public
          enable_jekyll: true
          remove_path_spec: 'next/integrations/r/'

  build_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm i -g yarn
      - run: yarn set version berry
      - run: yarn config set checksumBehavior ignore
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ./.yarn
          key: ${{ runner.os }}-yarn2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-
      - run: yarn install --immutable
        env:
          CI: true
      - run: yarn build
        env:
          CI: true
      - run: yarn lint
        env:
          CI: true
      # - run: yarn test --ci --coverage --maxWorkers=2
      #   env:
      #     CI: true
