name: ci

on: [push]

jobs:
  build_r:
    runs-on: ubuntu-16.04
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: https://demo.rstudiopm.com/all/__linux__/xenial/latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 3.6
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: linux-r3.6-${{ hashFiles('DESCRIPTION') }}
          restore-keys: linux-r3.6-

      - name: Install dependencies
        run: |
          remotes::install_cran("devtools")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        run: devtools::check(args = "--no-manual", error_on = "error", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r3.6-results
          path: check

  build_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm i -g yarn
      - run: yarn set version berry
      - run: yarn plugin import @yarnpkg/plugin-workspace-tools
      - run: yarn config set checksumBehavior ignore
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ./.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --immutable
        env:
          CI: true
      - run: yarn build
        env:
          CI: true
      - run: yarn lint
        env:
          CI: true
      # - run: yarn test --ci --coverage --maxWorkers=2
      #   env:
      #     CI: true
