name: ci

on: [push]

jobs:
  build_r:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
        # build client code
      - run: npm i -g yarn
      - run: yarn config set checksumBehavior ignore
      - name: Cache Node.js modules
        uses: actions/cache@v2.1.6
        with:
          path: |
            ./.yarn/cache
            ./.yarn/unplugged
          key: ${{ runner.os }}-yarn2-v4-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-v4
      - run: yarn install
      - run: yarn build
      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-v2-${{ hashFiles('r_package/DESCRIPTION')}}
          restore-keys: ${{ runner.os }}-r-v2-

      # - name: Install system dependencies
      #   env:
      #     RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
      #   run: |
      #     Rscript -e "remotes::install_github('r-hub/sysreqs')"
      #     sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
      #     sudo -s eval "$sysreqs"
      - name: Install System dependencies
        run: |
          sudo apt-get install libgit2-dev libssl-dev

      - name: Install dependencies
        shell: Rscript {0}
        run: |
          install.packages(c('devtools', 'webshot', 'textshaping', 'stringi'))
          devtools::install_deps('r_package', dependencies = TRUE)

      - name: Style / Format
        shell: Rscript {0}
        run: styler::style_pkg('r_package', dry="fail")

      - name: Lint
        shell: Rscript {0}
        run: |
          devtools::load_all('r_package')
          lintr::lint_package('r_package')

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        shell: Rscript {0}
        run: devtools::check('r_package', args = c("--no-manual", "--as-cran"), error_on = "error", check_dir = "check")

      - name: Test
        shell: Rscript {0}
        run: devtools::test('r_package')

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-results
          path: r_package/check

      - name: Build Package
        run: yarn build:r
      - name: Prepare Docs
        run: |
          mkdir -p public/integrations/r
          cp ./upsetjs.tar.gz public/integrations/r/
          cp README.md r_package/
      - name: Build Website
        run: yarn docs:r
      - name: Copy Docs
        run: |
          mv r_package/docs/* public/integrations/r/

      - name: Deploy Main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: upsetjs/actions-gh-pages@sgratzl
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: upsetjs/upsetjs.github.io
          publish_branch: master
          publish_dir: ./public
          enable_jekyll: true
          remove_path_spec: 'integrations/r/'

      - if: github.ref == 'refs/heads/develop'
        # move to next directory
        run: |
          mv public public2
          mkdir -p public
          mv public2 public/next

      - name: Deploy Develop
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        uses: upsetjs/actions-gh-pages@sgratzl
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: upsetjs/upsetjs.github.io
          publish_branch: master
          publish_dir: ./public
          enable_jekyll: true
          remove_path_spec: 'next/integrations/r/'

  build_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
        # build client code
      - run: npm i -g yarn
      - run: yarn config set checksumBehavior ignore
      - name: Cache Node.js modules
        uses: actions/cache@v2.1.6
        with:
          path: |
            ./.yarn/cache
            ./.yarn/unplugged
          key: ${{ runner.os }}-yarn2-v4-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-v4
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      # - run: yarn test --ci --coverage --maxWorkers=2
